global:
  scrape_interval: 1m

scrape_configs:
  # Job for Prometheus itself
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]

  # --- PI 5 Metrics ---
  - job_name: "pi5-node"
    static_configs:
      - targets: ["node-exporter:9100"] # Node exporter on Ubuntu
        labels:
          instance: "raspberry-pi-5"

  # --- Ubuntu Server Metrics ---
  - job_name: "ubuntu-node"
    static_configs:
      - targets: ["<UBUNTU_IP>:9100"] # Node exporter on Ubuntu
        labels:
          instance: "ubuntu-server"

  # - job_name: 'ubuntu-cadvisor'
  # static_configs:
  # - targets: ['<UBUNTU_IP>:8081'] # cAdvisor on Ubuntu

  # --- LinuxMint Metrics ---
  - job_name: "lm-node"
    static_configs:
      - targets: ["<LM_IP>:9100"] # Node exporter on 'linux-mint'
        labels:
          instance: "linux-mint"

  # --- TrueNAS Metrics ---
  - job_name: "tn-node"
    static_configs:
      - targets: ["<TN_IP>:9100"] # Node exporter on RPi
        labels:
          instance: "truenas-scale"

  # --- PVECompute Metrics ---
  - job_name: "pvecompute-node"
    static_configs:
      - targets: ["<PVE_IP>:9100"] # Node exporter on RPi
        labels:
          instance: "pve-compute"

  # --- Debian-Sceptre Metrics ---
  - job_name: "sceptre-node"
    static_configs:
      - targets: ["<SCEPTRE_IP>:9100"] # Node exporter on RPi
        labels:
          instance: "debian-sceptre"
